// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ir.university.toosi.tms.readerwrapper;

import java.io.Serializable;

public class AccessEventData implements Serializable {
    int userID;
    String date;
    String time;
    //    byte virduAuthMode;
//    byte authType;
    boolean authorized;
    String rfid;
    int picLenght;
    byte[] pictureData;
    int totalNumber;
    int currentIndex;
    int errorCode;
    String fingerImageFormat;
    int fingerImageLenght;
    byte[] fingerImageData;

    public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    //    public byte getVirduAuthMode() {
//        return virduAuthMode;
//    }
//
//    public void setVirduAuthMode(byte virduAuthMode) {
//        this.virduAuthMode = virduAuthMode;
//    }
//
    public boolean isAuthorized() {
        return authorized;
    }

    public void setAuthorized(boolean authorized) {
        this.authorized = authorized;
    }

    public String getRfid() {
        return rfid;
    }

    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    public int getPicLenght() {
        return picLenght;
    }

    public void setPicLenght(int picLenght) {
        this.picLenght = picLenght;
    }

    public byte[] getPictureData() {
        return pictureData;
    }

    public void setPictureData(byte[] pictureData) {
        this.pictureData = pictureData;
    }

    public int getTotalNumber() {
        return totalNumber;
    }

    public void setTotalNumber(int totalNumber) {
        this.totalNumber = totalNumber;
    }

    public int getCurrentIndex() {
        return currentIndex;
    }

    public void setCurrentIndex(int currentIndex) {
        this.currentIndex = currentIndex;
    }

    public int getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

    public String getFingerImageFormat() {
        return fingerImageFormat;
    }

    public void setFingerImageFormat(String fingerImageFormat) {
        this.fingerImageFormat = fingerImageFormat;
    }

    public int getFingerImageLenght() {
        return fingerImageLenght;
    }

    public void setFingerImageLenght(int fingerImageLenght) {
        this.fingerImageLenght = fingerImageLenght;
    }

    public byte[] getFingerImageData() {
        return fingerImageData;
    }

    public void setFingerImageData(byte[] fingerImageData) {
        this.fingerImageData = fingerImageData;
    }
}
