// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ir.university.toosi.tms.readerwrapper;

@net.sf.jni4net.attributes.ClrType
public class EnumHelper extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected EnumHelper(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected EnumHelper() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LReaderWrapper/DeviceType;)LSystem/String;")
    public native static String GetTitle(DeviceType deviceType);
    
    @net.sf.jni4net.attributes.ClrMethod("(IIIIII)LReaderWrapper/AuthenticationType;")
    public native static AuthenticationType GetEnumValue(int isAndOperation, int isFinger, int isCard, int isPassword, int isCardId, int isFpCard);
    
    public static system.Type typeof() {
        return EnumHelper.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        EnumHelper.staticType = staticType;
    }
    //</generated-proxy>
}
