// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ir.university.toosi.tms.readerwrapper;

import java.io.Serializable;

public class Person_ implements Serializable{

    int userId;
    String userName;
    String EmplymentCode;

    public Person_() {
    }


    public native int getUserIdforTerminal();
    
    public native void setUserIdforTerminal(int value);
    
    public native String getUserName();

    public native void setUserName(String value);

    public native String getEmploymentCode();

    public native void setEmploymentCode(String value);

    public native String getAccessGroup();

    public native void setAccessGroup(String value);

    public native AccessDateType getAccessDateType();

    public native void setAccessDateType(AccessDateType value);

    public native system.DateTime getStartAccessDate();

    public native void setStartAccessDate(system.DateTime value);

    public native system.DateTime getEndAccessDate();

    public native void setEndAccessDate(system.DateTime value);

    public native AuthenticationType getAuthenticationType();

    public native void setAuthenticationType(AuthenticationType value);

    public native String getPasswordForTerminal();

    public native void setPasswordForTerminal(String value);

    public native byte[] getPicture();

    public native void setPicture(byte[] value);

    public native String[] getCards();

    public native void setCards(String[] value);
    
    public native byte[] getFingerprints();
    
    public native void setFingerprints(byte[] value);
    
}
