//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 03:47:05 PM IRDT 
//


package ir.university.toosi.tms.model.entity.objectValue.alert;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="node_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertlastname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertpersonnum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertdatetime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertimageurl" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertdiffusecolor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertnotiftitle" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertnotifdescription" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="alertnotifimageurl" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "number")
public class Number {

    @XmlAttribute(name = "node_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String nodeId;
    @XmlAttribute(name = "alertname")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertname;
    @XmlAttribute(name = "alertlastname")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertlastname;
    @XmlAttribute(name = "alertpersonnum")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertpersonnum;
    @XmlAttribute(name = "alertdatetime")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertdatetime;
    @XmlAttribute(name = "alertimageurl")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertimageurl;
    @XmlAttribute(name = "alertdiffusecolor")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertdiffusecolor;
    @XmlAttribute(name = "alertnotiftitle")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertnotiftitle;
    @XmlAttribute(name = "alertnotifdescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertnotifdescription;
    @XmlAttribute(name = "alertnotifimageurl")
    @XmlSchemaType(name = "anySimpleType")
    protected String alertnotifimageurl;

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the alertname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertname() {
        return alertname;
    }

    /**
     * Sets the value of the alertname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertname(String value) {
        this.alertname = value;
    }

    /**
     * Gets the value of the alertlastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertlastname() {
        return alertlastname;
    }

    /**
     * Sets the value of the alertlastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertlastname(String value) {
        this.alertlastname = value;
    }

    /**
     * Gets the value of the alertpersonnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertpersonnum() {
        return alertpersonnum;
    }

    /**
     * Sets the value of the alertpersonnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertpersonnum(String value) {
        this.alertpersonnum = value;
    }

    /**
     * Gets the value of the alertdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertdatetime() {
        return alertdatetime;
    }

    /**
     * Sets the value of the alertdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertdatetime(String value) {
        this.alertdatetime = value;
    }

    /**
     * Gets the value of the alertimageurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertimageurl() {
        return alertimageurl;
    }

    /**
     * Sets the value of the alertimageurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertimageurl(String value) {
        this.alertimageurl = value;
    }

    /**
     * Gets the value of the alertdiffusecolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertdiffusecolor() {
        return alertdiffusecolor;
    }

    /**
     * Sets the value of the alertdiffusecolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertdiffusecolor(String value) {
        this.alertdiffusecolor = value;
    }

    /**
     * Gets the value of the alertnotiftitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertnotiftitle() {
        return alertnotiftitle;
    }

    /**
     * Sets the value of the alertnotiftitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertnotiftitle(String value) {
        this.alertnotiftitle = value;
    }

    /**
     * Gets the value of the alertnotifdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertnotifdescription() {
        return alertnotifdescription;
    }

    /**
     * Sets the value of the alertnotifdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertnotifdescription(String value) {
        this.alertnotifdescription = value;
    }

    /**
     * Gets the value of the alertnotifimageurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertnotifimageurl() {
        return alertnotifimageurl;
    }

    /**
     * Sets the value of the alertnotifimageurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertnotifimageurl(String value) {
        this.alertnotifimageurl = value;
    }

}
