//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.06 at 12:01:51 PM IRDT 
//


package ir.university.toosi.tms.model.entity.objectValue.init;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dd" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NodeName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="translation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="rotation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DEF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "dd"
})
@XmlRootElement(name = "cc")
public class Cc {

    @XmlElement(required = true)
    protected Dd dd;
    @XmlAttribute(name = "NodeName")
    @XmlSchemaType(name = "anySimpleType")
    protected String nodeName;
    @XmlAttribute(name = "scale")
    @XmlSchemaType(name = "anySimpleType")
    protected String scale;
    @XmlAttribute(name = "translation")
    @XmlSchemaType(name = "anySimpleType")
    protected String translation;
    @XmlAttribute(name = "rotation")
    @XmlSchemaType(name = "anySimpleType")
    protected String rotation;
    @XmlAttribute(name = "DEF")
    @XmlSchemaType(name = "anySimpleType")
    protected String def;

    /**
     * Gets the value of the dd property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Dd getDd() {
        return dd;
    }

    /**
     * Sets the value of the dd property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setDd(Dd value) {
        this.dd = value;
    }

    /**
     * Gets the value of the nodeName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * Sets the value of the nodeName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNodeName(String value) {
        this.nodeName = value;
    }

    /**
     * Gets the value of the scale property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScale(String value) {
        this.scale = value;
    }

    /**
     * Gets the value of the translation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTranslation() {
        return translation;
    }

    /**
     * Sets the value of the translation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTranslation(String value) {
        this.translation = value;
    }

    /**
     * Gets the value of the rotation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRotation(String value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the def property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDEF() {
        return def;
    }

    /**
     * Sets the value of the def property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDEF(String value) {
        this.def = value;
    }

}
