//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.06 at 12:01:51 PM IRDT 
//


package ir.university.toosi.tms.model.entity.objectValue.init;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ee" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ff" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NodeName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="isPickable" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DEF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ee",
        "ff"
})
@XmlRootElement(name = "dd")
public class Dd {

    @XmlElement(required = true)
    protected Ee ee;
    @XmlElement(required = true)
    protected Ff ff;
    @XmlAttribute(name = "NodeName")
    @XmlSchemaType(name = "anySimpleType")
    protected String nodeName;
    @XmlAttribute(name = "isPickable")
    @XmlSchemaType(name = "anySimpleType")
    protected String isPickable;
    @XmlAttribute(name = "DEF")
    @XmlSchemaType(name = "anySimpleType")
    protected String def;

    /**
     * Gets the value of the ee property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Ee getEe() {
        return ee;
    }

    /**
     * Sets the value of the ee property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setEe(Ee value) {
        this.ee = value;
    }

    /**
     * Gets the value of the ff property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Ff getFf() {
        return ff;
    }

    /**
     * Sets the value of the ff property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setFf(Ff value) {
        this.ff = value;
    }

    /**
     * Gets the value of the nodeName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * Sets the value of the nodeName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNodeName(String value) {
        this.nodeName = value;
    }

    /**
     * Gets the value of the isPickable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsPickable() {
        return isPickable;
    }

    /**
     * Sets the value of the isPickable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsPickable(String value) {
        this.isPickable = value;
    }

    /**
     * Gets the value of the def property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDEF() {
        return def;
    }

    /**
     * Sets the value of the def property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDEF(String value) {
        this.def = value;
    }

}
